/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Kelvin Bonilla
 */
public class StoreArrayFrame extends javax.swing.JFrame
{

    private final javax.swing.JFrame MAIN_MENU;
    /**
     * Creates new form StoreArrayFrame
     */
    public StoreArrayFrame(javax.swing.JFrame mainMenu) {
        initComponents();
        MAIN_MENU = mainMenu;
        setAllToolTips();
    }

    private void setAllToolTips() {
        numElementsLbl.setToolTipText("This determines the number of elements the array will have, as well as the range of numbers the array will store (from 0 to 10/100/1000)");
        arrayNameLbl.setToolTipText("The name that this array will be associated with back in the main menu.");
        submitBtn.setToolTipText("Stores the array with the properties chosen.");
        backBtn.setToolTipText("Closes this window and returns you back to the \"Array or Integer?\" window.");
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numElementBtnGroup = new javax.swing.ButtonGroup();
        tenElementsRadioBtn = new javax.swing.JRadioButton();
        hunElementsRadioBtn = new javax.swing.JRadioButton();
        thouElementsRadioBtn = new javax.swing.JRadioButton();
        numElementsLbl = new javax.swing.JLabel();
        arrayNameLbl = new javax.swing.JLabel();
        arrayNameTxtField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Store An Array");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingEvt(evt);
            }
        });

        numElementBtnGroup.add(tenElementsRadioBtn);
        tenElementsRadioBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tenElementsRadioBtn.setText("10");

        numElementBtnGroup.add(hunElementsRadioBtn);
        hunElementsRadioBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        hunElementsRadioBtn.setText("100");

        numElementBtnGroup.add(thouElementsRadioBtn);
        thouElementsRadioBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        thouElementsRadioBtn.setText("1000");

        numElementsLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numElementsLbl.setText("Number of Elements:");

        arrayNameLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        arrayNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        arrayNameLbl.setText("Name of The Array:");

        arrayNameTxtField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        arrayNameTxtField.setText("[Enter Name Here]");
        arrayNameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldFocusGained(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBtn)
                        .addGap(18, 18, 18)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(arrayNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numElementsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tenElementsRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hunElementsRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thouElementsRadioBtn))
                            .addComponent(arrayNameTxtField))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hunElementsRadioBtn)
                    .addComponent(tenElementsRadioBtn)
                    .addComponent(thouElementsRadioBtn)
                    .addComponent(numElementsLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrayNameLbl)
                    .addComponent(arrayNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(submitBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldFocusGained
        if (evt.getComponent() instanceof javax.swing.JTextField)
        {
            javax.swing.JTextField tf = (javax.swing.JTextField) evt.getComponent();
            tf.selectAll();
        }
    }//GEN-LAST:event_txtFieldFocusGained

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Not Supported Yet", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        
        // Reminders: Reset Text Field Text
        //            Return Information To The Main Menu
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        TitleFrameApp.displayFrame(new Array_Integer_Popup(MAIN_MENU), this);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void windowClosingEvt(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingEvt
        TitleFrameApp.displayFrame(new Array_Integer_Popup(MAIN_MENU), this);
        dispose();
    }//GEN-LAST:event_windowClosingEvt

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrayNameLbl;
    private javax.swing.JTextField arrayNameTxtField;
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton hunElementsRadioBtn;
    private javax.swing.ButtonGroup numElementBtnGroup;
    private javax.swing.JLabel numElementsLbl;
    private javax.swing.JButton submitBtn;
    private javax.swing.JRadioButton tenElementsRadioBtn;
    private javax.swing.JRadioButton thouElementsRadioBtn;
    // End of variables declaration//GEN-END:variables
}
